# Generated by Django 4.1.7 on 2023-07-17 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth', '0002_alter_oauthqquser_openid_alter_oauthqquser_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oauthqquser',
            name='create_time',
            field=models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='oauthqquser',
            name='update_time',
            field=models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间'),
        ),
    ]
