# Generated by Django 4.1.7 on 2023-07-17 19:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContentCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('key', models.CharField(help_text='类别键名', max_length=50, verbose_name='类别键名')),
            ],
            options={
                'verbose_name': '广告内容类别',
                'verbose_name_plural': '广告内容类别',
                'db_table': 'tb_content_category',
            },
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('title', models.CharField(help_text='标题', max_length=100, verbose_name='标题')),
                ('url', models.CharField(help_text='内容链接', max_length=300, verbose_name='内容链接')),
                ('image', models.ImageField(blank=True, help_text='图片', null=True, upload_to='', verbose_name='图片')),
                ('text', models.TextField(blank=True, help_text='内容', null=True, verbose_name='内容')),
                ('sequence', models.IntegerField(help_text='排序', verbose_name='排序')),
                ('status', models.BooleanField(default=True, help_text='是否展示', verbose_name='是否展示')),
                ('category', models.ForeignKey(help_text='类别', on_delete=django.db.models.deletion.PROTECT, to='contents.contentcategory', verbose_name='类别')),
            ],
            options={
                'verbose_name': '广告内容',
                'verbose_name_plural': '广告内容',
                'db_table': 'tb_content',
            },
        ),
    ]
