# Generated by Django 4.1.7 on 2023-07-17 19:23

import ckeditor.fields
import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=20, verbose_name='名称')),
                ('logo', models.ImageField(help_text='Logo图片', upload_to='', verbose_name='Logo图片')),
                ('first_letter', models.CharField(help_text='品牌首字母', max_length=1, verbose_name='品牌首字母')),
            ],
            options={
                'verbose_name': '品牌',
                'verbose_name_plural': '品牌',
                'db_table': 'tb_brand',
            },
        ),
        migrations.CreateModel(
            name='GoodsCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=10, verbose_name='名称')),
                ('parent', models.ForeignKey(blank=True, help_text='父类别', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subs', to='goods.goodscategory', verbose_name='父类别')),
            ],
            options={
                'verbose_name': '商品类别',
                'verbose_name_plural': '商品类别',
                'db_table': 'tb_goods_category',
            },
        ),
        migrations.CreateModel(
            name='GoodsChannelGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='频道组名', max_length=20, verbose_name='频道组名')),
            ],
            options={
                'verbose_name': '商品频道组',
                'verbose_name_plural': '商品频道组',
                'db_table': 'tb_channel_group',
            },
        ),
        migrations.CreateModel(
            name='SKU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('caption', models.CharField(help_text='副标题', max_length=100, verbose_name='副标题')),
                ('price', models.DecimalField(decimal_places=2, help_text='单价', max_digits=10, verbose_name='单价')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='进价', max_digits=10, verbose_name='进价')),
                ('market_price', models.DecimalField(decimal_places=2, help_text='市场价', max_digits=10, verbose_name='市场价')),
                ('stock', models.IntegerField(default=0, help_text='库存', verbose_name='库存')),
                ('sales', models.IntegerField(default=0, help_text='销量', verbose_name='销量')),
                ('comments', models.IntegerField(default=0, help_text='评价数', verbose_name='评价数')),
                ('is_launched', models.BooleanField(default=True, help_text='是否上架销售', verbose_name='是否上架销售')),
                ('default_image', models.ImageField(blank=True, default='', help_text='默认图片', max_length=200, null=True, upload_to='', verbose_name='默认图片')),
                ('category', models.ForeignKey(help_text='从属类别', on_delete=django.db.models.deletion.PROTECT, to='goods.goodscategory', verbose_name='从属类别')),
            ],
            options={
                'verbose_name': '商品SKU',
                'verbose_name_plural': '商品SKU',
                'db_table': 'tb_sku',
            },
        ),
        migrations.CreateModel(
            name='SPU',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='名称', max_length=50, verbose_name='名称')),
                ('sales', models.IntegerField(default=0, help_text='销量', verbose_name='销量')),
                ('comments', models.IntegerField(default=0, help_text='评价数', verbose_name='评价数')),
                ('desc_detail', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='详细介绍', verbose_name='详细介绍')),
                ('desc_pack', ckeditor.fields.RichTextField(default='', help_text='包装信息', verbose_name='包装信息')),
                ('desc_service', ckeditor_uploader.fields.RichTextUploadingField(default='', help_text='售后服务', verbose_name='售后服务')),
                ('brand', models.ForeignKey(help_text='品牌', on_delete=django.db.models.deletion.PROTECT, to='goods.brand', verbose_name='品牌')),
                ('category1', models.ForeignKey(help_text='一级类别', on_delete=django.db.models.deletion.PROTECT, related_name='cat1_spu', to='goods.goodscategory', verbose_name='一级类别')),
                ('category2', models.ForeignKey(help_text='二级类别', on_delete=django.db.models.deletion.PROTECT, related_name='cat2_spu', to='goods.goodscategory', verbose_name='二级类别')),
                ('category3', models.ForeignKey(help_text='三级类别', on_delete=django.db.models.deletion.PROTECT, related_name='cat3_spu', to='goods.goodscategory', verbose_name='三级类别')),
            ],
            options={
                'verbose_name': '商品SPU',
                'verbose_name_plural': '商品SPU',
                'db_table': 'tb_spu',
            },
        ),
        migrations.CreateModel(
            name='SPUSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('name', models.CharField(help_text='规格名称', max_length=20, verbose_name='规格名称')),
                ('spu', models.ForeignKey(help_text='商品SPU', on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.spu', verbose_name='商品SPU')),
            ],
            options={
                'verbose_name': '商品SPU规格',
                'verbose_name_plural': '商品SPU规格',
                'db_table': 'tb_spu_specification',
            },
        ),
        migrations.CreateModel(
            name='SpecificationOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('value', models.CharField(help_text='选项值', max_length=20, verbose_name='选项值')),
                ('spec', models.ForeignKey(help_text='规格', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='goods.spuspecification', verbose_name='规格')),
            ],
            options={
                'verbose_name': '规格选项',
                'verbose_name_plural': '规格选项',
                'db_table': 'tb_specification_option',
            },
        ),
        migrations.CreateModel(
            name='SKUSpecification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('option', models.ForeignKey(help_text='规格值', on_delete=django.db.models.deletion.PROTECT, to='goods.specificationoption', verbose_name='规格值')),
                ('sku', models.ForeignKey(help_text='sku', on_delete=django.db.models.deletion.CASCADE, related_name='specs', to='goods.sku', verbose_name='sku')),
                ('spec', models.ForeignKey(help_text='规格名称', on_delete=django.db.models.deletion.PROTECT, to='goods.spuspecification', verbose_name='规格名称')),
            ],
            options={
                'verbose_name': 'SKU规格',
                'verbose_name_plural': 'SKU规格',
                'db_table': 'tb_sku_specification',
            },
        ),
        migrations.CreateModel(
            name='SKUImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('image', models.ImageField(help_text='图片', upload_to='', verbose_name='图片')),
                ('sku', models.ForeignKey(help_text='sku', on_delete=django.db.models.deletion.CASCADE, to='goods.sku', verbose_name='sku')),
            ],
            options={
                'verbose_name': 'SKU图片',
                'verbose_name_plural': 'SKU图片',
                'db_table': 'tb_sku_image',
            },
        ),
        migrations.AddField(
            model_name='sku',
            name='spu',
            field=models.ForeignKey(help_text='商品', on_delete=django.db.models.deletion.CASCADE, to='goods.spu', verbose_name='商品'),
        ),
        migrations.CreateModel(
            name='GoodsVisitCount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('count', models.IntegerField(default=0, help_text='访问量', verbose_name='访问量')),
                ('date', models.DateField(auto_now_add=True, help_text='统计日期', verbose_name='统计日期')),
                ('category', models.ForeignKey(help_text='商品分类', on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='商品分类')),
            ],
            options={
                'verbose_name': '统计分类商品访问量',
                'verbose_name_plural': '统计分类商品访问量',
                'db_table': 'tb_goods_visit',
            },
        ),
        migrations.CreateModel(
            name='GoodsChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, help_text='修改时间', verbose_name='修改时间')),
                ('url', models.CharField(help_text='频道页面链接', max_length=50, verbose_name='频道页面链接')),
                ('sequence', models.IntegerField(help_text='组内顺序', verbose_name='组内顺序')),
                ('category', models.ForeignKey(help_text='顶级商品类别', on_delete=django.db.models.deletion.CASCADE, to='goods.goodscategory', verbose_name='顶级商品类别')),
                ('group', models.ForeignKey(help_text='频道组名', on_delete=django.db.models.deletion.CASCADE, to='goods.goodschannelgroup', verbose_name='频道组名')),
            ],
            options={
                'verbose_name': '商品频道',
                'verbose_name_plural': '商品频道',
                'db_table': 'tb_goods_channel',
            },
        ),
    ]
