# Generated by Django 4.1.7 on 2023-07-16 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email_active',
            field=models.BooleanField(default=False, help_text='邮箱激活状态', verbose_name='邮箱激活状态'),
        ),
    ]
